using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TestPlatform : MonoBehaviour
{
    [SerializeField] PlatformManager platform;
    [SerializeField] Unit unit;

    // Start is called before the first frame update
    void Start()
    {
        //РЏДжРЧ УЪБт РЇФЁ СіСЄ
        unit.transform.position = new Vector3(0, -4, 0);
        //platformРЧ НУРлРЇФЁПЭ АЃАнРЛ МГСЄ
        platform.MakePlatforms(1, 2);
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButtonUp(0))
        {
            //РЏДж СЁЧС - platformРЧ АЃАнКИДй СЖБн ГєАд СЁЧС
            unit.Jump(2.2f);
        }

        //РЏДжРЧ ЧіРчРЇФЁЗЮ ЙпЦЧРЛ АЛНХЧиСиДй
        platform.UpdatePlatform(unit.transform.position.y);
    }
}
